import { z } from "zod";

import { Pool, Source, Tier } from "./common.js";

/**
 * Metric definitions shared by the pipeline (which extracts raw values from nflverse data) and
 * the grading engine (which owns the weights and turns values into percentiles and grades).
 * Keys are `<pool>.<metric>`; the pipeline must emit exactly these keys per player or unit.
 *
 * `direction: "lower"` means a lower raw value is better (sack rate, drops, missed tackles).
 * `tier: "final"` metrics come from PFR advanced stats and are absent in provisional grades.
 */
export const MetricDef = z.object({
  key: z.string(),
  label: z.string(),
  pool: Pool,
  source: Source,
  direction: z.enum(["higher", "lower"]),
  tier: Tier,
  unit: z.enum(["rate", "pct", "epa", "yds", "count", "score"]),
  /** Shown in the UI so every grade is explainable. */
  description: z.string(),
});
export type MetricDef = z.infer<typeof MetricDef>;

const m = (
  key: string,
  label: string,
  pool: Pool,
  source: Source,
  direction: "higher" | "lower",
  tier: Tier,
  unit: MetricDef["unit"],
  description: string,
): MetricDef => ({ key, label, pool, source, direction, tier, unit, description });

/** Every graded metric, grouped by pool. Weights live in @huddle/grades. */
export const METRICS: readonly MetricDef[] = [
  // QB (qualifies at >= 14 dropbacks)
  m(
    "qb.epaPerDropback",
    "EPA per dropback",
    "QB",
    "pbp",
    "higher",
    "provisional",
    "epa",
    "Sum of qb_epa on dropbacks divided by dropbacks.",
  ),
  m(
    "qb.successRate",
    "Dropback success rate",
    "QB",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Share of dropbacks with positive EPA.",
  ),
  m(
    "qb.cpoe",
    "Completion % over expected",
    "QB",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Mean cpoe on pass attempts (sacks excluded).",
  ),
  m(
    "qb.sackRate",
    "Sack rate",
    "QB",
    "pbp",
    "lower",
    "provisional",
    "pct",
    "Sacks per dropback, excluding sacks FTN charts as not the QB's fault.",
  ),
  m(
    "qb.turnoverWorthyRate",
    "Turnover-worthy play rate",
    "QB",
    "ftn",
    "lower",
    "provisional",
    "pct",
    "FTN interception-worthy throws plus lost fumbles per dropback.",
  ),
  m(
    "qb.badThrowPct",
    "Bad throw %",
    "QB",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR passing_bad_throw_pct.",
  ),
  m(
    "qb.ngsCpoe",
    "NGS completion % above expectation",
    "QB",
    "ngs",
    "higher",
    "provisional",
    "pct",
    "NGS completion_percentage_above_expectation (qualifying QBs only).",
  ),
  // RB (qualifies at >= 6 carries or >= 8 touches)
  m(
    "rb.rushEpaPerAtt",
    "Rush EPA per attempt",
    "RB",
    "stats_player",
    "higher",
    "provisional",
    "epa",
    "rushing_epa divided by carries.",
  ),
  m(
    "rb.successRate",
    "Rush success rate",
    "RB",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Share of designed carries with positive EPA.",
  ),
  m(
    "rb.ryoePerAtt",
    "Rush yards over expected per attempt",
    "RB",
    "ngs",
    "higher",
    "provisional",
    "yds",
    "NGS rush_yards_over_expected_per_att, or explosive-run rate when NGS is missing.",
  ),
  m(
    "rb.contact",
    "Yards after contact + broken tackles",
    "RB",
    "pfr",
    "higher",
    "final",
    "yds",
    "PFR rushing_yards_after_contact_avg plus broken tackles per carry.",
  ),
  m(
    "rb.recEpaPerTarget",
    "Receiving EPA per target",
    "RB",
    "stats_player",
    "higher",
    "provisional",
    "epa",
    "receiving_epa divided by targets.",
  ),
  // WR / TE (qualifies at >= 15 offensive snaps or >= 3 targets)
  m(
    "wr.recEpaPerTarget",
    "Receiving EPA per target",
    "WR",
    "stats_player",
    "higher",
    "provisional",
    "epa",
    "receiving_epa divided by targets.",
  ),
  m(
    "wr.yardsPerEstRoute",
    "Yards per estimated route",
    "WR",
    "snap_counts",
    "higher",
    "provisional",
    "yds",
    "Receiving yards per estimated route (snaps × team dropback share); true routes are post-season only.",
  ),
  m(
    "wr.targetShare",
    "Target share",
    "WR",
    "stats_player",
    "higher",
    "provisional",
    "pct",
    "target_share.",
  ),
  m(
    "wr.catchRateOverExpected",
    "Catch rate over expected",
    "WR",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Sum of complete_pass minus cp over targets.",
  ),
  m(
    "wr.yacOverExpected",
    "YAC over expected",
    "WR",
    "ngs",
    "higher",
    "provisional",
    "yds",
    "NGS avg_yac_above_expectation, or pbp yac_epa minus xyac_epa when NGS is missing.",
  ),
  m(
    "wr.dropRate",
    "Drop rate",
    "WR",
    "ftn",
    "lower",
    "provisional",
    "pct",
    "FTN drops per catchable target.",
  ),
  m(
    "wr.contestedCatchRate",
    "Contested catch rate",
    "WR",
    "ftn",
    "higher",
    "provisional",
    "pct",
    "FTN contested targets caught.",
  ),
  m(
    "te.recEpaPerTarget",
    "Receiving EPA per target",
    "TE",
    "stats_player",
    "higher",
    "provisional",
    "epa",
    "receiving_epa divided by targets.",
  ),
  m(
    "te.yardsPerEstRoute",
    "Yards per estimated route",
    "TE",
    "snap_counts",
    "higher",
    "provisional",
    "yds",
    "Receiving yards per estimated route.",
  ),
  m(
    "te.targetShare",
    "Target share",
    "TE",
    "stats_player",
    "higher",
    "provisional",
    "pct",
    "target_share.",
  ),
  m(
    "te.catchRateOverExpected",
    "Catch rate over expected",
    "TE",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Sum of complete_pass minus cp over targets.",
  ),
  m(
    "te.yacOverExpected",
    "YAC over expected",
    "TE",
    "ngs",
    "higher",
    "provisional",
    "yds",
    "NGS avg_yac_above_expectation or pbp fallback.",
  ),
  m(
    "te.dropRate",
    "Drop rate",
    "TE",
    "ftn",
    "lower",
    "provisional",
    "pct",
    "FTN drops per catchable target.",
  ),
  m(
    "te.contestedCatchRate",
    "Contested catch rate",
    "TE",
    "ftn",
    "higher",
    "provisional",
    "pct",
    "FTN contested targets caught.",
  ),
  // OL unit (32 teams)
  m(
    "ol.pressureRateAllowed",
    "Pressure rate allowed",
    "OL",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR times_pressured over team dropbacks; provisional proxy is (sacks + QB hits) per dropback.",
  ),
  m(
    "ol.sackRate",
    "Sack rate allowed",
    "OL",
    "pbp",
    "lower",
    "provisional",
    "pct",
    "Sacks per dropback, excluding QB-fault sacks.",
  ),
  m(
    "ol.protectionVsFour",
    "Protection vs four rushers",
    "OL",
    "ftn",
    "lower",
    "provisional",
    "pct",
    "Sacks + hits per dropback when FTN counts four or fewer pass rushers.",
  ),
  m(
    "ol.yardsBeforeContact",
    "Rush yards before contact",
    "OL",
    "pfr",
    "higher",
    "final",
    "yds",
    "PFR rushing_yards_before_contact per carry for the team's backs.",
  ),
  m(
    "ol.stuffRate",
    "Stuff rate",
    "OL",
    "pbp",
    "lower",
    "provisional",
    "pct",
    "Designed runs stopped for no gain or a loss.",
  ),
  m(
    "ol.adjustedLineYards",
    "Adjusted line yards",
    "OL",
    "pbp",
    "higher",
    "provisional",
    "yds",
    "Line-credited rushing yards (0-4 full, 5-10 half, negatives 1.2×).",
  ),
  // EDGE and IDL (qualify at >= 15 defensive snaps)
  m(
    "edge.pressureRate",
    "Pressure rate",
    "EDGE",
    "pfr",
    "higher",
    "final",
    "pct",
    "PFR def_pressures per estimated pass-rush snap.",
  ),
  m(
    "edge.sacks",
    "Sacks",
    "EDGE",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_sacks (half sacks count half).",
  ),
  m(
    "edge.qbHits",
    "QB hits",
    "EDGE",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_qb_hits.",
  ),
  m(
    "edge.tfl",
    "Tackles for loss",
    "EDGE",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_tackles_for_loss.",
  ),
  m(
    "edge.runStopRate",
    "Run stop rate",
    "EDGE",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Tackles on unsuccessful designed runs per run snap.",
  ),
  m(
    "edge.missedTacklePct",
    "Missed tackle %",
    "EDGE",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_missed_tackle_pct.",
  ),
  m(
    "idl.pressureRate",
    "Pressure rate",
    "IDL",
    "pfr",
    "higher",
    "final",
    "pct",
    "PFR def_pressures per estimated pass-rush snap.",
  ),
  m("idl.sacks", "Sacks", "IDL", "stats_player", "higher", "provisional", "count", "def_sacks."),
  m(
    "idl.qbHits",
    "QB hits",
    "IDL",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_qb_hits.",
  ),
  m(
    "idl.tfl",
    "Tackles for loss",
    "IDL",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_tackles_for_loss.",
  ),
  m(
    "idl.runStopRate",
    "Run stop rate",
    "IDL",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Tackles on unsuccessful designed runs per run snap.",
  ),
  m(
    "idl.missedTacklePct",
    "Missed tackle %",
    "IDL",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_missed_tackle_pct.",
  ),
  // LB (qualifies at >= 20 defensive snaps)
  m(
    "lb.runStopRate",
    "Run stop rate",
    "LB",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Tackles on unsuccessful designed runs per run snap.",
  ),
  m(
    "lb.tacklesPerSnap",
    "Tackles per snap",
    "LB",
    "stats_player",
    "higher",
    "provisional",
    "rate",
    "Solo tackles plus half of assists per defensive snap.",
  ),
  m(
    "lb.tflPlusSacks",
    "TFL + sacks",
    "LB",
    "stats_player",
    "higher",
    "provisional",
    "count",
    "def_tackles_for_loss plus def_sacks.",
  ),
  m(
    "lb.missedTacklePct",
    "Missed tackle %",
    "LB",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_missed_tackle_pct.",
  ),
  m(
    "lb.coverage",
    "Coverage",
    "LB",
    "pfr",
    "lower",
    "final",
    "score",
    "Yards allowed per target blended with passer rating allowed (needs 2+ targets).",
  ),
  m(
    "lb.blitzPressureRate",
    "Blitz pressure rate",
    "LB",
    "pfr",
    "higher",
    "final",
    "pct",
    "PFR def_pressures per def_times_blitzed.",
  ),
  // CB and S (qualify at >= 20 defensive snaps; coverage needs 3+ targets)
  m(
    "cb.yardsPerCoverageSnap",
    "Yards allowed per coverage snap",
    "CB",
    "pfr",
    "lower",
    "final",
    "yds",
    "PFR def_yards_allowed per defensive snap.",
  ),
  m(
    "cb.passerRatingAllowed",
    "Passer rating allowed",
    "CB",
    "pfr",
    "lower",
    "final",
    "score",
    "PFR def_passer_rating_allowed.",
  ),
  m(
    "cb.completionPctAllowed",
    "Completion % allowed",
    "CB",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_completion_pct.",
  ),
  m(
    "cb.ballProduction",
    "Ball production",
    "CB",
    "pbp",
    "higher",
    "provisional",
    "rate",
    "Interceptions plus pass breakups per estimated coverage snap.",
  ),
  m(
    "cb.missedTacklePct",
    "Missed tackle %",
    "CB",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_missed_tackle_pct.",
  ),
  m(
    "cb.tdAllowed",
    "TDs allowed",
    "CB",
    "pfr",
    "lower",
    "final",
    "count",
    "PFR def_receiving_td_allowed.",
  ),
  m(
    "s.yardsPerCoverageSnap",
    "Yards allowed per coverage snap",
    "S",
    "pfr",
    "lower",
    "final",
    "yds",
    "PFR def_yards_allowed per defensive snap.",
  ),
  m(
    "s.passerRatingAllowed",
    "Passer rating allowed",
    "S",
    "pfr",
    "lower",
    "final",
    "score",
    "PFR def_passer_rating_allowed.",
  ),
  m(
    "s.completionPctAllowed",
    "Completion % allowed",
    "S",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_completion_pct.",
  ),
  m(
    "s.ballProduction",
    "Ball production",
    "S",
    "pbp",
    "higher",
    "provisional",
    "rate",
    "Interceptions plus pass breakups per estimated coverage snap.",
  ),
  m(
    "s.missedTacklePct",
    "Missed tackle %",
    "S",
    "pfr",
    "lower",
    "final",
    "pct",
    "PFR def_missed_tackle_pct.",
  ),
  m(
    "s.tdAllowed",
    "TDs allowed",
    "S",
    "pfr",
    "lower",
    "final",
    "count",
    "PFR def_receiving_td_allowed.",
  ),
  // Specialists
  m(
    "k.fgPointsOverExpected",
    "FG points over expected",
    "K",
    "pbp",
    "higher",
    "provisional",
    "score",
    "Made × 3 minus expected points from a distance/roof make table fit on 2016-2025.",
  ),
  m(
    "k.xpRate",
    "Extra point rate",
    "K",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "extra_point_result made share.",
  ),
  m(
    "k.kickoffTouchbackRate",
    "Kickoff touchback rate",
    "K",
    "pbp",
    "higher",
    "provisional",
    "pct",
    "Touchbacks per kickoff (short-of-landing-zone penalties count against).",
  ),
  m(
    "p.netAvg",
    "Net punt average",
    "P",
    "stats_player",
    "higher",
    "provisional",
    "yds",
    "pt_net_yards per punt.",
  ),
  m(
    "p.inside20Rate",
    "Inside-20 rate",
    "P",
    "stats_player",
    "higher",
    "provisional",
    "pct",
    "pt_inside_20 per punt.",
  ),
  m(
    "p.puntEpa",
    "Punt EPA",
    "P",
    "pbp",
    "higher",
    "provisional",
    "epa",
    "EPA on punt plays from the punting team's perspective.",
  ),
  m(
    "ret.returnEpa",
    "Return EPA",
    "RET",
    "pbp",
    "higher",
    "provisional",
    "epa",
    "EPA credited to the returning team on returns.",
  ),
  m(
    "ret.yardsPerReturn",
    "Yards per return",
    "RET",
    "pbp",
    "higher",
    "provisional",
    "yds",
    "Return yards per return.",
  ),
];

export const METRIC_KEYS = METRICS.map((d) => d.key);

export function metricsForPool(pool: Pool): readonly MetricDef[] {
  return METRICS.filter((d) => d.pool === pool);
}

const byKey = new Map(METRICS.map((d) => [d.key, d] as const));
export function metricDef(key: string): MetricDef | undefined {
  return byKey.get(key);
}
